classDiagram
    class MetadataNode {
        int fs_capacity
        size_t num_blocks
        bitmap_t *bitmap
        int *block_mapping

        int num_files
        FileEntry *files

        int num_nodes
        DataNode *nodes
        NodeConnection *connections
        int *blocks_per_node
        int *blocks_free

        blocks_per_node : mapping<int node_id, int num_blocks>
    }